# before committing check this file here: https://lint.travis-ci.org/

language: python

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=coverage
  - python: 3.2
    env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0" STVER="<30.0.0"
  - python: 3.3
    env: TOXENV=py33
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: nightly
    env: TOXENV=py37
  - python: 2.7
    env: TOXENV=pep8
  - python: 3.5
    env: TOXENV=pep8
  - python: 3.5
    env: TOXENV=packaging
  allow_failures:
  - python: 3.2
    env: TOXENV=py32 VENVVER="<14.0.0" PIPVER="<8.0.0" STVER="<30.0.0"
  - python: nightly
    env: TOXENV=py37

# travis-ci runs by default on ancient Ubuntu 12.04 (precise)
# following options will give us Ubuntu 14.04 (trusty)
dist: trusty

# we will use faster container infrastructure
sudo: false

install:
- pip install --upgrade virtualenv$VENVVER pip$PIPVER setuptools$STVER tox wheel

script:
- tox --notest && travis_retry tox tests/*.py
