# validation page for appveyor config: https://ci.appveyor.com/tools/validate-yaml

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# check also https://github.com/BjornFJohansson/seguid_calculator/blob/master/appveyor.yml

# we are not building Visual Studio project, so default build step is off
build: off

# encrypting data done here: https://ci.appveyor.com/tools/encrypt
environment:

  matrix:
#    # http://www.appveyor.com/docs/installed-software#python
    - platform: x86
      PYTHON_ROOT: "C:\\Python27"
      PYTHON_VERSION: "2.7"
      MINICONDAPATH: "C:\\Miniconda"
    - platform: x64
      PYTHON_ROOT: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7"
      MINICONDAPATH: "C:\\Miniconda-x64"

init:
# add Python interpreter to PATH variable
  - set PATH=%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
# add Miniconda to PATH variable
  - set PATH=%MINICONDAPATH%\Scripts;%PATH%
# following this one: https://github.com/audreyr/cookiecutter/issues/599
  - "git config --system http.sslcainfo \"C:\\Program Files\\Git\\mingw64\\ssl\\certs\\ca-bundle.crt\""
# check python version
  - python -V
# check 32 or 64 bit
  - python -c "import struct;print(8 * struct.calcsize('P'))"

install:
# tell miniconda to always follow default answers
  - conda config --set always_yes yes --set changeps1 no
# create new conda workspace and activate it
  - conda create -q --name python%PYTHON_VERSION% python=%PYTHON_VERSION%
  - activate python%PYTHON_VERSION%
# as scipy and classic wxpython doesn't yet have wheels for windows, install it using conda
  - conda install -q --name python%PYTHON_VERSION% numpy
# install usual requirements
  - pip install -r requirements.txt
# check numpy & scipy versions
  - python -c "import numpy as np;print(np.version.version)"
# check python version
  - python -V
# check 32 or 64 bit
  - python -c "import struct;print(8 * struct.calcsize('P'))"

test_script:
  - FOR %%I in (tests\test*.py) DO python -m pytest %%I
